# Generated by Django 3.0.6 on 2020-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200510_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
